# Generated by Django 4.0.6 on 2022-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('boughtFor', models.IntegerField()),
                ('hold', models.BooleanField(default=True)),
            ],
        ),
    ]
