# Generated by Django 4.0.6 on 2022-07-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elysium_app', '0005_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
