# Generated by Django 4.0.6 on 2023-03-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elysium_app', '0007_remove_clientinfo_capital_remove_review_avg_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientInfo',
            new_name='PlatformInfo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='active',
        ),
    ]
