# Generated by Django 4.0.6 on 2023-03-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elysium_app', '0008_rename_clientinfo_platforminfo_remove_stock_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforminfo',
            name='description',
        ),
    ]
