# Generated by Django 4.0.6 on 2023-05-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elysium_app', '0012_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
    ]
